name: FACEBOOK REEL SCHEDULER

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '30 11 * * *'  # Runs at 5:00 PM IST
  #   - cron: '30 15 * * *'   # Runs at 9:00 PM IST
  
jobs:
  run-script:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      # Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          repository: XorVision/xorvision
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          sparse-checkout: |
            FACEBOOK/
            VIDEO_EDITING_QUALITY/
            counter.txt
            requirements.txt
          fetch-depth: 1

      # Read the counter value and set sparse-checkout for the specific reel
      - name: Configure Sparse Checkout for Specific Reel
        run: |
          REEL_NUMBER=$(cat counter.txt)
          echo "Setting sparse-checkout for reel_${REEL_NUMBER}.mp4"
          echo "REELS/reel_${REEL_NUMBER}.mp4" >> .git/info/sparse-checkout
          git sparse-checkout reapply
          
      # Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.9'  # Specify the Python version you need

      # Install the necessary packages
      - name: Installed package list
        run: apt list --installed

      # Install dependencies
      - name: Install dependencies
        run: |
         python3 -m pip install --upgrade pip
         pip3 install -r requirements.txt

      # Run your Python script
      - name: Run Python script
        run: python3 FACEBOOK/facebook.py
        
      # Check if .env has been modified, pull, and push the modified changes.
      - name: Commit and Push Changes
        run: |
          git config --local user.name "github-actions"
          git config --local user.email "github-actions@github.com"
          git add FACEBOOK/.env
          git commit -m "Update .env after processing" || echo "No changes to commit"
          git pull --rebase origin main || echo "No changes to pull"
          git push || echo "No changes to push"
